-- app_data
CREATE USER app_data IDENTIFIED BY "sYPvydx"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_code
CREATE USER app_code IDENTIFIED BY "7ipnMbH+s"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_admin
CREATE USER app_admin IDENTIFIED BY "5U8eFH"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_user
CREATE USER app_user IDENTIFIED BY "+aVKXFbcUV"
ENABLE EDITIONS;